version: "3.9"

services:
  cinema-dbc:
    image: mysql
    container_name: cinema-dbc
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: maria
      MYSQL_DATABASE: cinemadb
      MYSQL_USER: manager
      MYSQL_PASSWORD: manager
    volumes:
      - ./db-data:/var/lib/mysql
